### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by SuperGrobi** [SuperGrobi/Leaflet.jl#3]
- [ ] figure out the basics of jsserve
- [ ] repurpose Layer and Map types to setup simple test object
- [ ] setup bidirectional interaction (probably mostly js to jl. The other way should be taken care of mostly by observables? I think?)
- [ ] Taking html screenshots would be nice...

What else?
